//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakingScience.Users.Data
{
    using System;
    
    public enum UserType : short
    {
        Admin = 0,
        Assistant = 1,
        Student = 2
    }
}
